{!! Html::script('js_admin/jquery.min.js') !!}
{!! Html::script('js_admin/bootstrap.min.js') !!}
{!! Html::script('js_admin/fastclick.js') !!}
{!! Html::script('js_admin/nprogress.js') !!}
{!! Html::script('js_admin/bootstrap-progressbar.min.js') !!}
{!! Html::script('js_admin/icheck.min.js') !!}
{!! Html::script('js_admin/moment.min.js') !!}
{!! Html::script('js_admin/daterangepicker.js') !!}
{!! Html::script('js_admin/bootstrap-wysiwyg.min.js') !!}
{!! Html::script('js_admin/jquery.hotkeys.js') !!}
{!! Html::script('js_admin/prettify.js') !!}
{!! Html::script('js_admin/jquery.tagsinput.js') !!}
{!! Html::script('js_admin/switchery.min.js') !!}
{!! Html::script('js_admin/select2.full.min.js') !!}
{!! Html::script('js_admin/parsley.min.js') !!}
{!! Html::script('js_admin/autosize.min.js') !!}
{!! Html::script('js_admin/jquery.autocomplete.min.js') !!}
{!! Html::script('js_admin/starrr.js') !!}
{!! Html::script('js_admin/custom.min.js') !!}
